"""Prompt research: seed term -> candidate prompts worth tracking.

Two independent, honestly-separate signals:
  1. Candidate prompts + why they're relevant — generated by Groq (fast, free
     tier, open-weight models). This is AI brainstorming, not measured data.
  2. Search interest — real relative-interest scores from Google Trends
     (via the unofficial pytrends client), scoped to the market the caller
     is researching for. This is a genuine external signal, but it measures
     literal Google search behavior, not "AI prompt volume" — no such data
     exists anywhere publicly. We look up the short `search_query` Groq
     extracts per candidate (not the full conversational prompt), since
     natural-language questions rarely match how people actually type into
     Google.

Never present search_interest as AI-prompt traffic — it isn't.
"""

import asyncio
import json
from typing import Any, TypedDict

import httpx

from config import GROQ_API_KEY, GROQ_MODEL
from countries import country_name

_GROQ_ENDPOINT = "https://api.groq.com/openai/v1/chat/completions"
INTENTS = ["Commercial", "Informational", "Transactional", "Navigational"]


class PromptCandidate(TypedDict):
    prompt_text: str
    topic: str
    search_query: str
    intent: str
    relevance_note: str
    search_interest: int | None


async def _generate_candidates(
    seed: str, brand_name: str, domain: str, country: str
) -> list[dict[str, Any]]:
    if not GROQ_API_KEY:
        return []

    schema_hint = (
        '{"candidates": [{"prompt_text": string, "topic": string (2-4 words), '
        '"search_query": string (short, how someone would actually type this into '
        'a search engine, 2-5 words), "intent": one of '
        f"{INTENTS}, "
        '"relevance_note": string (1 sentence: why this is worth tracking for the brand)}]}'
    )
    prompt = (
        f"You help a brand called '{brand_name}' ({domain}) find questions people ask AI "
        f"assistants (ChatGPT, Gemini) that relate to '{seed}' and that the brand's own "
        "content could realistically get cited for. Generate 8 realistic, varied candidate "
        "prompts — mix of buying-guide, comparison, and informational questions, phrased the "
        "way a real user would ask an AI assistant. Do not include the brand name itself in "
        "every prompt; most real prompts are category-level, not brand-specific.\n\n"
        f"The audience is in {country_name(country)} — favour phrasing, product names, and "
        "retailers a user there would actually use.\n\n"
        f"Respond with ONLY valid JSON matching this shape, nothing else:\n{schema_hint}"
    )

    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            resp = await client.post(
                _GROQ_ENDPOINT,
                headers={"Authorization": f"Bearer {GROQ_API_KEY}", "Content-Type": "application/json"},
                json={
                    "model": GROQ_MODEL,
                    "messages": [{"role": "user", "content": prompt}],
                    "response_format": {"type": "json_object"},
                    "temperature": 0.6,
                },
            )
        if resp.status_code != 200:
            return []
        data = resp.json()
        text = data["choices"][0]["message"]["content"]
        parsed = json.loads(text)
    except (httpx.HTTPError, KeyError, IndexError, json.JSONDecodeError):
        return []

    candidates = parsed.get("candidates")
    if not isinstance(candidates, list):
        return []

    out = []
    for c in candidates:
        if not isinstance(c, dict) or not c.get("prompt_text") or not c.get("search_query"):
            continue
        intent = c.get("intent")
        out.append(
            {
                "prompt_text": str(c["prompt_text"]),
                "topic": str(c.get("topic") or ""),
                "search_query": str(c["search_query"]),
                "intent": intent if intent in INTENTS else "Informational",
                "relevance_note": str(c.get("relevance_note") or ""),
            }
        )
    return out


def _fetch_search_interest_sync(queries: list[str], country: str) -> dict[str, int | None]:
    """Blocking pytrends call — Google Trends compares at most 5 terms per
    request, and the client itself is synchronous, so this runs in a thread.
    Unofficial API: can fail or rate-limit; callers must treat None as
    "unknown", never as zero interest."""
    from pytrends.request import TrendReq

    results: dict[str, int | None] = {q: None for q in queries}
    try:
        pytrends = TrendReq(hl="en-US", tz=330)
        for i in range(0, len(queries), 5):
            batch = queries[i : i + 5]
            pytrends.build_payload(batch, timeframe="today 3-m", geo=country)
            df = pytrends.interest_over_time()
            if df is None or df.empty:
                continue
            for q in batch:
                if q in df.columns:
                    results[q] = int(round(df[q].mean()))
    except Exception:
        pass  # unofficial endpoint — leave remaining entries as None (unknown)
    return results


async def research_prompts(
    seed: str, brand_name: str, domain: str, country: str
) -> list[PromptCandidate]:
    candidates = await _generate_candidates(seed, brand_name, domain, country)
    if not candidates:
        return []

    queries = [c["search_query"] for c in candidates]
    interest = await asyncio.to_thread(_fetch_search_interest_sync, queries, country)

    return [
        PromptCandidate(
            prompt_text=c["prompt_text"],
            topic=c["topic"],
            search_query=c["search_query"],
            intent=c["intent"],
            relevance_note=c["relevance_note"],
            search_interest=interest.get(c["search_query"]),
        )
        for c in candidates
    ]
